export const USE_CASES_SEED = [
  {
    title: 'AI-Powered Lead Qualification',
    description: 'Automatically score and route inbound leads so your team focuses only on the hottest prospects.',
    detail: 'Using AI to analyze lead behavior, demographics, and engagement signals, you can prioritize outreach and reduce time wasted on unqualified contacts.',
    industries: ['All'],
    functions: ['Sales'],
    estimated_roi: '35% higher close rate',
    time_savings: 'Saves 5 hrs/week',
    complexity: 'low',
  },
  {
    title: 'Automated Customer Follow-Up',
    description: 'AI sends personalized follow-up emails and messages at the right time — without your team lifting a finger.',
    detail: 'Trigger sequences based on customer behavior, purchase history, or inactivity. Each message feels personal because it is.',
    industries: ['Retail', 'Professional Services', 'Restaurant/Hospitality'],
    functions: ['Customer Service', 'Sales'],
    estimated_roi: '30% higher retention',
    time_savings: 'Saves 4 hrs/week',
    complexity: 'low',
  },
  {
    title: 'Invoice & Expense Automation',
    description: 'Automatically extract, categorize, and process invoices and expenses — eliminating manual data entry.',
    detail: 'AI reads invoices from email or uploads, categorizes line items, and syncs with your accounting software.',
    industries: ['All'],
    functions: ['Finance'],
    estimated_roi: '80% faster processing',
    time_savings: 'Saves 4 hrs/week',
    complexity: 'low',
  },
  {
    title: 'AI Appointment Scheduling',
    description: 'Let AI handle the back-and-forth of booking appointments, reminders, and rescheduling.',
    detail: 'Integrates with your calendar and sends automated reminders to reduce no-shows significantly.',
    industries: ['Healthcare', 'Professional Services', 'Restaurant/Hospitality'],
    functions: ['Operations', 'Customer Service'],
    estimated_roi: 'Reduces no-shows 25%',
    time_savings: 'Saves 3 hrs/week',
    complexity: 'low',
  },
  {
    title: 'Social Media Content Generation',
    description: 'AI drafts on-brand posts, captions, and content calendars based on your business and goals.',
    detail: 'Provide your brand voice and topics — AI generates a week of content in minutes for your review.',
    industries: ['All'],
    functions: ['Marketing'],
    estimated_roi: '3x more consistent posting',
    time_savings: 'Saves 6 hrs/week',
    complexity: 'low',
  },
  {
    title: 'Predictive Inventory Management',
    description: 'AI forecasts demand and flags low stock before it becomes a problem.',
    detail: 'By analyzing sales trends, seasonality, and supplier lead times, AI recommends optimal reorder points.',
    industries: ['Retail', 'Manufacturing'],
    functions: ['Operations'],
    estimated_roi: '20% reduction in stockouts',
    time_savings: 'Saves 3 hrs/week',
    complexity: 'medium',
  },
  {
    title: 'AI Customer Support Chat',
    description: 'An AI assistant handles common customer questions 24/7, escalating only what truly needs a human.',
    detail: 'Trained on your FAQs, policies, and product info, the AI resolves tier-1 tickets instantly.',
    industries: ['All'],
    functions: ['Customer Service'],
    estimated_roi: 'Handles 60% of tier-1 tickets',
    time_savings: 'Saves 8 hrs/week',
    complexity: 'medium',
  },
  {
    title: 'Proposal & Estimate Generation',
    description: 'AI drafts professional proposals and estimates from a few inputs in minutes.',
    detail: 'Pull in job details, pricing templates, and client history — AI builds a polished proposal ready to send.',
    industries: ['Professional Services', 'Manufacturing', 'Real Estate'],
    functions: ['Sales'],
    estimated_roi: '50% faster proposal turnaround',
    time_savings: 'Saves 5 hrs/week',
    complexity: 'low',
  },
  {
    title: 'Review Response Automation',
    description: 'AI crafts personalized, on-brand responses to customer reviews across Google, Yelp, and more.',
    detail: 'Respond to every review within hours — positive or negative — with a tone that matches your brand.',
    industries: ['Restaurant/Hospitality', 'Retail', 'Professional Services'],
    functions: ['Marketing', 'Customer Service'],
    estimated_roi: '4.5+ average star rating',
    time_savings: 'Saves 2 hrs/week',
    complexity: 'low',
  },
  {
    title: 'Employee Onboarding Assistant',
    description: 'An AI guide walks new hires through onboarding, answers questions, and tracks their progress.',
    detail: 'New employees get instant answers about policies, tools, and processes without waiting for HR.',
    industries: ['All'],
    functions: ['HR'],
    estimated_roi: '40% faster time-to-productivity',
    time_savings: 'Saves 6 hrs per hire',
    complexity: 'medium',
  },
  {
    title: 'AI-Powered Market Analysis',
    description: 'AI researches competitors, pricing trends, and market shifts so you can act on insights — not guesses.',
    detail: 'Get weekly or on-demand reports summarizing what is happening in your market and what it means for your business.',
    industries: ['All'],
    functions: ['Sales', 'Marketing'],
    estimated_roi: 'Faster strategic decisions',
    time_savings: 'Saves 5 hrs/week',
    complexity: 'medium',
  },
  {
    title: 'Document Summarization & Search',
    description: 'AI reads, summarizes, and lets you search across all your business documents in plain English.',
    detail: 'Contracts, reports, emails — ask a question and get an instant answer with source references.',
    industries: ['All'],
    functions: ['Operations', 'Finance'],
    estimated_roi: '70% faster document review',
    time_savings: 'Saves 4 hrs/week',
    complexity: 'low',
  },
  {
    title: 'Predictive Maintenance Alerts',
    description: 'AI monitors equipment data and alerts your team before a breakdown happens.',
    detail: 'Sensors and historical data train the model to spot failure patterns weeks in advance.',
    industries: ['Manufacturing'],
    functions: ['Operations'],
    estimated_roi: '30% reduction in downtime',
    time_savings: 'Prevents costly repairs',
    complexity: 'high',
  },
  {
    title: 'AI-Driven Pricing Optimization',
    description: 'Dynamically adjust pricing based on demand, competitor pricing, and inventory levels.',
    detail: 'AI recommends price changes in real time to maximize margin without losing customers.',
    industries: ['Retail', 'Restaurant/Hospitality'],
    functions: ['Operations', 'Finance'],
    estimated_roi: '8–15% margin improvement',
    time_savings: 'Saves 3 hrs/week',
    complexity: 'high',
  },
  {
    title: 'Personalized Email Campaigns',
    description: 'AI segments your audience and writes personalized emails for each group — at scale.',
    detail: 'Each subscriber gets content relevant to their behavior and preferences, not a one-size-fits-all blast.',
    industries: ['All'],
    functions: ['Marketing'],
    estimated_roi: '2x open rates',
    time_savings: 'Saves 4 hrs/week',
    complexity: 'medium',
  },
  {
    title: 'AI Financial Reporting',
    description: 'Automatically generate P&L summaries, cash flow forecasts, and KPI dashboards from your data.',
    detail: 'Get plain-English explanations of your financial position without waiting for your accountant.',
    industries: ['All'],
    functions: ['Finance'],
    estimated_roi: 'Real-time financial clarity',
    time_savings: 'Saves 6 hrs/month',
    complexity: 'medium',
  },
  {
    title: 'Patient Documentation Automation',
    description: 'AI transcribes and structures clinical notes, freeing providers to focus on care.',
    detail: 'Voice-to-text with AI structuring turns conversations into formatted EHR entries automatically.',
    industries: ['Healthcare'],
    functions: ['Operations'],
    estimated_roi: '2 hrs saved per provider/day',
    time_savings: 'Saves 10 hrs/week',
    complexity: 'medium',
  },
  {
    title: 'Property Listing Descriptions',
    description: 'AI generates compelling, SEO-optimized property listings from photos and specs in seconds.',
    detail: 'Input the details; AI writes descriptions that highlight features buyers care about.',
    industries: ['Real Estate'],
    functions: ['Marketing'],
    estimated_roi: '20% faster time on market',
    time_savings: 'Saves 2 hrs per listing',
    complexity: 'low',
  },
  {
    title: 'Client Reporting Automation',
    description: 'AI compiles campaign results, analytics, and insights into polished client reports automatically.',
    detail: 'Connect your data sources and let AI do the number-crunching and narrative writing every month.',
    industries: ['Marketing/Agency'],
    functions: ['Operations', 'Marketing'],
    estimated_roi: '75% faster report production',
    time_savings: 'Saves 8 hrs/month per client',
    complexity: 'medium',
  },
  {
    title: 'AI-Powered Job Matching',
    description: 'AI screens resumes and matches candidates to open roles based on skills, experience, and culture fit.',
    detail: 'Reduce time-to-hire by surfacing the best candidates automatically from your applicant pool.',
    industries: ['All'],
    functions: ['HR'],
    estimated_roi: '50% faster hiring',
    time_savings: 'Saves 6 hrs per role',
    complexity: 'medium',
  },
  {
    title: 'Supply Chain Risk Monitoring',
    description: 'AI monitors supplier news, weather, and geopolitical signals to flag supply chain risks before they hit.',
    detail: 'Get early warnings so you can diversify suppliers or adjust inventory before a disruption.',
    industries: ['Manufacturing', 'Retail'],
    functions: ['Operations'],
    estimated_roi: 'Prevents costly disruptions',
    time_savings: 'Saves hours of monitoring',
    complexity: 'high',
  },
  {
    title: 'AI Sales Call Coaching',
    description: 'AI analyzes sales call recordings and gives reps personalized coaching tips to close more deals.',
    detail: 'Identify talk patterns, objection handling gaps, and missed opportunities automatically.',
    industries: ['All'],
    functions: ['Sales'],
    estimated_roi: '20% improvement in close rate',
    time_savings: 'Saves manager review time',
    complexity: 'medium',
  },
  {
    title: 'Menu & Pricing Intelligence',
    description: 'AI analyzes sales data and customer feedback to recommend menu changes that boost profit.',
    detail: 'Know which items to promote, price, or retire based on data — not gut feel.',
    industries: ['Restaurant/Hospitality'],
    functions: ['Operations', 'Marketing'],
    estimated_roi: '10–15% revenue increase',
    time_savings: 'Saves 3 hrs/month',
    complexity: 'medium',
  },
  {
    title: 'Loan & Credit Risk Analysis',
    description: 'AI evaluates loan applications and credit risk faster and more consistently than manual review.',
    detail: 'Score applicants against multiple risk factors simultaneously for faster, fairer decisions.',
    industries: ['Finance'],
    functions: ['Operations', 'Finance'],
    estimated_roi: '60% faster decisions',
    time_savings: 'Saves 4 hrs per application',
    complexity: 'high',
  },
  {
    title: 'AI Content Repurposing',
    description: 'Turn one piece of content — a blog post, video, or podcast — into 10 assets across every channel.',
    detail: 'AI extracts key points and reformats into social posts, email snippets, and short-form video scripts.',
    industries: ['Marketing/Agency', 'All'],
    functions: ['Marketing'],
    estimated_roi: '5x content output',
    time_savings: 'Saves 5 hrs per content piece',
    complexity: 'low',
  },
]
